# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: redns 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "redns".freeze
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["tadman".freeze]
  s.date = "2017-09-14"
  s.description = "ReDNS is a pure Ruby DNS library with drivers for reactor-model engines such as EventMachine".freeze
  s.email = "github@tadman.ca".freeze
  s.executables = ["redig".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/redig",
    "lib/redns.rb",
    "lib/redns/address.rb",
    "lib/redns/buffer.rb",
    "lib/redns/connection.rb",
    "lib/redns/fragment.rb",
    "lib/redns/message.rb",
    "lib/redns/name.rb",
    "lib/redns/question.rb",
    "lib/redns/record.rb",
    "lib/redns/record/mx.rb",
    "lib/redns/record/null.rb",
    "lib/redns/record/soa.rb",
    "lib/redns/record/spf.rb",
    "lib/redns/record/txt.rb",
    "lib/redns/resolver.rb",
    "lib/redns/resource.rb",
    "lib/redns/support.rb",
    "redns.gemspec",
    "test/helper.rb",
    "test/test_redns.rb",
    "test/test_redns_address.rb",
    "test/test_redns_buffer.rb",
    "test/test_redns_connection.rb",
    "test/test_redns_fragment.rb",
    "test/test_redns_message.rb",
    "test/test_redns_name.rb",
    "test/test_redns_question.rb",
    "test/test_redns_resolver.rb",
    "test/test_redns_resource.rb",
    "test/test_redns_support.rb"
  ]
  s.homepage = "http://github.com/tadman/redns".freeze
  s.rubygems_version = "2.6.11".freeze
  s.summary = "Ruby Reactor-Ready DNS Library".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<eventmachine>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rake>.freeze, [">= 0"])
      s.add_dependency(%q<eventmachine>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>.freeze, [">= 0"])
    s.add_dependency(%q<eventmachine>.freeze, [">= 0"])
  end
end

