# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redns}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tadman"]
  s.date = %q{2010-08-13}
  s.description = %q{ReDNS is a pure Ruby DNS library with drivers for reactor-model engines such as EventMachine}
  s.email = %q{github@tadman.ca}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/redns.rb",
     "lib/redns/address.rb",
     "lib/redns/buffer.rb",
     "lib/redns/fragment.rb",
     "lib/redns/message.rb",
     "lib/redns/name.rb",
     "lib/redns/question.rb",
     "lib/redns/record.rb",
     "lib/redns/record/mx.rb",
     "lib/redns/record/null.rb",
     "lib/redns/record/soa.rb",
     "lib/redns/resource.rb",
     "lib/redns/support.rb",
     "redns.gemspec",
     "test/helper.rb",
     "test/test_redns.rb",
     "test/test_redns_address.rb",
     "test/test_redns_buffer.rb",
     "test/test_redns_fragment.rb",
     "test/test_redns_message.rb",
     "test/test_redns_name.rb",
     "test/test_redns_question.rb",
     "test/test_redns_resource.rb",
     "test/test_redns_support.rb"
  ]
  s.homepage = %q{http://github.com/tadman/redns}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby Reactor-Ready DNS Library}
  s.test_files = [
    "test/helper.rb",
     "test/test_redns.rb",
     "test/test_redns_address.rb",
     "test/test_redns_buffer.rb",
     "test/test_redns_fragment.rb",
     "test/test_redns_message.rb",
     "test/test_redns_name.rb",
     "test/test_redns_question.rb",
     "test/test_redns_resource.rb",
     "test/test_redns_support.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

