# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "redns"
  s.version = "0.1.18"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tadman"]
  s.date = "2013-09-18"
  s.description = "ReDNS is a pure Ruby DNS library with drivers for reactor-model engines such as EventMachine"
  s.email = "github@tadman.ca"
  s.executables = ["redig"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/redig",
    "lib/redns.rb",
    "lib/redns/address.rb",
    "lib/redns/buffer.rb",
    "lib/redns/connection.rb",
    "lib/redns/fragment.rb",
    "lib/redns/message.rb",
    "lib/redns/name.rb",
    "lib/redns/question.rb",
    "lib/redns/record.rb",
    "lib/redns/record/mx.rb",
    "lib/redns/record/null.rb",
    "lib/redns/record/soa.rb",
    "lib/redns/record/spf.rb",
    "lib/redns/record/txt.rb",
    "lib/redns/resolver.rb",
    "lib/redns/resource.rb",
    "lib/redns/support.rb",
    "redns.gemspec",
    "test/helper.rb",
    "test/test_redns.rb",
    "test/test_redns_address.rb",
    "test/test_redns_buffer.rb",
    "test/test_redns_connection.rb",
    "test/test_redns_fragment.rb",
    "test/test_redns_message.rb",
    "test/test_redns_name.rb",
    "test/test_redns_question.rb",
    "test/test_redns_resolver.rb",
    "test/test_redns_resource.rb",
    "test/test_redns_support.rb"
  ]
  s.homepage = "http://github.com/tadman/redns"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Ruby Reactor-Ready DNS Library"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

